[package]
name = "asio_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows-targets = "0.48.1"
bitflags = "2.3.3"

[dependencies.windows]
version = "0.48"
features = ["Win32_System_Com"]
